name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      #      - name: Authenticate aws cli
      #        run: aws ecr get-login-password --region eu-north-1 | podman login --username AWS --password-stdin 475075013331.dkr.ecr.eu-north-1.amazonaws.com
      #      - name: Pull the image
      #        run: podman pull 475075013331.dkr.ecr.eu-north-1.amazonaws.com/okr/okrserver:latest
      #      - name: Delete old container
      #        run: podman rm -f okr/okrserver || true
      - name: check current working directory
        run: pwd
        working-directory: ${{ github.workspace }}/server-nest
      - name: run the container
        run: podman compose up
        working-directory: ${{ github.workspace }}/server-nest
