name: CI Pipeline

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=us-east-1" >> ~/.aws/config
        working-directory: ${{ github.workspace }}/server-nest
      - name: AWS Login
        run: aws ecr get-login-password --region eu-north-1 | podman login --username AWS --password-stdin 475075013331.dkr.ecr.eu-north-1.amazonaws.com
        working-directory: ${{ github.workspace }}/server-nest
      - name: Build the docker image
        run: podman build -t okr/okrserver .
        working-directory: ${{ github.workspace }}/server-nest
      - name: tag the image
        run: podman tag okr/okrserver:latest 475075013331.dkr.ecr.eu-north-1.amazonaws.com/okr/okrserver:latest
        working-directory: ${{ github.workspace }}/server-nest
      - name: push the image
        run: podman push 475075013331.dkr.ecr.eu-north-1.amazonaws.com/okr/okrserver:latest
        working-directory: ${{ github.workspace }}/server-nest
      

      
